name: Health Report Action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script
        env:
          NJU_USERNAME: ${{ secrets.username }}
          NJU_PASSWORD: ${{ secrets.password }}
          CURR_LOCATION: ${{ secrets.location }}
        run: |
          python run.py
